import type { Config } from 'tailwindcss';
import forms from '@tailwindcss/forms';
import containerQueries from '@tailwindcss/container-queries';

const config: Config = {
  darkMode: 'class',
  content: ['./app/**/*.{ts,tsx}', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'secondary-fixed': '#c3ecd7',
        'inverse-surface': '#2d3133',
        'on-secondary-fixed-variant': '#294e3f',
        'surface-dim': '#d8dadc',
        'on-surface': '#191c1e',
        'secondary-fixed-dim': '#a8cfbc',
        'on-background': '#191c1e',
        'inverse-primary': '#95d3ba',
        'primary-fixed-dim': '#95d3ba',
        background: '#f7f9fb',
        'surface-variant': '#e0e3e5',
        'on-surface-variant': '#404944',
        'on-primary-fixed': '#002117',
        surface: '#f7f9fb',
        'on-error': '#ffffff',
        error: '#ba1a1a',
        'surface-bright': '#f7f9fb',
        'on-error-container': '#93000a',
        'surface-container-highest': '#e0e3e5',
        'on-secondary': '#ffffff',
        tertiary: '#242f41',
        'on-primary-fixed-variant': '#0b513d',
        'surface-container-lowest': '#ffffff',
        'on-primary': '#ffffff',
        'error-container': '#ffdad6',
        'primary-fixed': '#b0f0d6',
        'primary-container': '#064e3b',
        'surface-container': '#eceef0',
        'tertiary-container': '#3a4558',
        'on-secondary-fixed': '#002115',
        'outline-variant': '#bfc9c3',
        'on-tertiary': '#ffffff',
        'inverse-on-surface': '#eff1f3',
        'surface-container-low': '#f2f4f6',
        outline: '#707974',
        secondary: '#416656',
        primary: '#003527',
        'on-tertiary-container': '#a7b2c9',
        'on-secondary-container': '#476c5b',
        'on-primary-container': '#80bea6',
        'tertiary-fixed-dim': '#bcc7de',
        'on-tertiary-fixed-variant': '#3c475a',
        'on-tertiary-fixed': '#111c2d',
        'tertiary-fixed': '#d8e3fb',
        'secondary-container': '#c3ecd7',
        'surface-container-high': '#e6e8ea',
        'surface-tint': '#2b6954',
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
      },
      spacing: {
        gutter: '24px',
        unit: '8px',
        'stack-sm': '8px',
        'stack-md': '24px',
        'margin-mobile': '20px',
        'container-max': '1280px',
        'stack-lg': '48px',
        'margin-desktop': '64px',
      },
      fontFamily: {
        'body-lg': ['var(--font-hanken)', 'sans-serif'],
        'headline-md': ['var(--font-playfair)', 'serif'],
        'display-lg-mobile': ['var(--font-playfair)', 'serif'],
        'headline-lg': ['var(--font-playfair)', 'serif'],
        'display-lg': ['var(--font-playfair)', 'serif'],
        'body-md': ['var(--font-hanken)', 'sans-serif'],
        'label-md': ['var(--font-hanken)', 'sans-serif'],
        'code-sm': ['var(--font-hanken)', 'sans-serif'],
      },
      fontSize: {
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-md': ['32px', { lineHeight: '1.3', fontWeight: '600' }],
        'display-lg-mobile': [
          '40px',
          { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '700' },
        ],
        'headline-lg': ['48px', { lineHeight: '1.2', fontWeight: '600' }],
        'display-lg': [
          '64px',
          { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' },
        ],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-md': [
          '14px',
          { lineHeight: '1.0', letterSpacing: '0.05em', fontWeight: '600' },
        ],
        'code-sm': ['13px', { lineHeight: '1.4', fontWeight: '500' }],
      },
      keyframes: {
        'scan-line': {
          '0%': { transform: 'translateY(-100%)', opacity: '0' },
          '10%': { opacity: '1' },
          '90%': { opacity: '1' },
          '100%': { transform: 'translateY(100vh)', opacity: '0' },
        },
        'progress-fill': {
          '0%': { width: '0%' },
          '50%': { width: '70%' },
          '100%': { width: '85%' },
        },
        shimmer: {
          '100%': { transform: 'translateX(100%)' },
        },
        pulse: {
          '0%, 100%': { transform: 'scale(0.95)' },
          '70%': { transform: 'scale(1)' },
        },
      },
      animation: {
        scan: 'scan-line 3s cubic-bezier(0.4, 0, 0.2, 1) infinite',
        progress: 'progress-fill 2s ease-out forwards',
        shimmer: 'shimmer 1.5s infinite',
      },
    },
  },
  plugins: [forms, containerQueries],
};

export default config;
